name: Generate Certificate Request and Create Pull Request

on:
  workflow_dispatch  # Adjust this if you use a different default branch

jobs:
  generate-csr-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get repository name
        id: repo-name
        run: echo "::set-output name=repo::${GITHUB_REPOSITORY#*/}"

      - name: Create directories
        run: mkdir -p .nextcloud/certificates

      - name: Generate certificate request and private key
        run: |
          openssl req -nodes -newkey rsa:4096 \
          -keyout .nextcloud/certificates/${{ steps.repo-name.outputs.repo }}.key \
          -out .nextcloud/certificates/${{ steps.repo-name.outputs.repo }}.csr \
          -subj "/CN=${{ steps.repo-name.outputs.repo }}"

      -       - name: Send private key via email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.USER_EMAIL_USER}}
          password: ${{secrets.USER_EMAIL_PASS}}
          subject: Private Key for ${{ steps.repo-name.outputs.repo }}
          body: Please find attached the private key for ${{ steps.repo-name.outputs.repo }}
          to: markwesterweel@conduction.nl
          from: GitHub Actions
          attachments: .nextcloud/certificates/${{ steps.repo-name.outputs.repo }}.key

      - name: Remove private key from repo
        run: rm .nextcloud/certificates/${{ steps.repo-name.outputs.repo }}.key

      - name: Fork target repository
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.rest.repos.createFork({
              owner: 'nextcloud',
              repo: 'app-certificate-requests',
            })

      - name: Checkout forked repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/app-certificate-requests
          path: app-certificate-requests

      - name: Copy CSR to forked repo
        run: |
          mkdir -p app-certificate-requests/${{ steps.repo-name.outputs.repo }}
          cp .nextcloud/certificates/${{ steps.repo-name.outputs.repo }}.csr app-certificate-requests/${{ steps.repo-name.outputs.repo }}/

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          path: app-certificate-requests
          commit-message: Add CSR for ${{ steps.repo-name.outputs.repo }}
          title: Add CSR for ${{ steps.repo-name.outputs.repo }}
          body: |
            This PR adds a Certificate Signing Request (CSR) for ${{ steps.repo-name.outputs.repo }}.
            
            Original repository: ${{ github.server_url }}/${{ github.repository }}
          branch: add-csr-${{ steps.repo-name.outputs.repo }}
          base: main
